#pragma once

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD

#ifdef MOUSEKEY_ENABLE
    #define MOUSEKEY_INTERVAL 16
    #define MOUSEKEY_DELAY 0
    #define MOUSEKEY_TIME_TO_MAX 60
    #define MOUSEKEY_MAX_SPEED 7
    #define MOUSEKEY_WHEEL_DELAY 0
#endif


